import type { Metadata } from "next";

import "./globals.css";
import Navber from "@/components/Navber";
import Footer from "@/components/Footer";
import Providers from "@/components/providers";

export const metadata: Metadata = {
  title: "BAKERY SHOP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative">
        <Providers>
          <Navber />
          <div className="py-36">{children}</div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
