import type { Metadata } from "next";

import "../style/globals.css";

import Footer from "@/components/Footer";
import AuthProviders from "libs/providers/auth/Provider";
import Providers from "libs/providers/providers";
import { Toaster } from "@/components/ui/toaster";
import Navber from "@/components/Navber";
export const metadata: Metadata = {
  title: "BAKERY SHOP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProviders>
      <html lang="en">
        <body>
          <Providers>
            <Navber />
            <Toaster />
            {children}
            <Footer />
          </Providers>
        </body>
      </html>
    </AuthProviders>
  );
}
