import React from "react";
import type { Metadata } from "next";
import "../style/globals.css";

export const metadata: Metadata = {
  title: "BAKERY SHOP",
  description: "Generated by create next app",
};
export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
